version: '3.3'

services:
  db:
    image: mysql:latest
    volumes:
      - ./flask/models:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_USER=mihal
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=zgtdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  # api:
    # build: ./flask
    # container_name: flask
    # restart: always
    # volumes:
      # - ./flask/:/app
    # environment:
      # - DB_HOST=db
    # expose:
      # - 5000

  fastapi:
    build: ./fastapi
    container_name: fastapi
    restart: always
    volumes:
      - ./fastapi/:/app
    environment:
      - DB_HOST=db
    expose:
      - 5000
  ui:
    build: ./vue/clie
    container_name: clie
    restart: always
    expose:
      - 80

  # ui:
    # build: 
      # context: ./zgt-react
      # args:
        # REACT_APP_API_HOST: "127.0.0.1"
    # container_name: react
    # restart: always
    # expose:
      # - 80

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"
      - "8080:80"